// Home page request
GET http://localhost:9000/

// Auth
// Author
// Swagger
// Redis


# ===== User API endpoint


###

GET http://localhost:9000/


###

# curl -X GET -i http://localhost:9000/quote/random -u "admin:admin"
GET http://localhost:9000/quote/random
Authorization: Basic admin admin

###

# curl -X GET -i http://localhost:9000/quote/random?rows=10 -u "admin:admin"
GET http://localhost:9000/quote/random?rows=10
Authorization: Basic admin admin

###

# curl -X GET -i http://localhost:9000/quote/e0a0c231-8b93-4bc5-8615-193e551a2703 -u "admin:admin"
GET http://localhost:9000/quote/e0a0c231-8b93-4bc5-8615-193e551a2703
Authorization: Basic admin admin

###

# curl -X GET -i http://localhost:9000/quote/genre/love -u "admin:admin"
GET http://localhost:9000/quote/genre/love
Authorization: Basic admin admin

###

// ###

# curl -X GET -i http://localhost:9000/quote/genre/love -u "admin:admin"
GET http://localhost:9000/quote/genre/love
Authorization: Basic admin admin

###

# curl -X GET -i http://localhost:9000/quote/genre-title/love -u "admin:admin"
GET http://localhost:9000/quote/genre-title/l
Authorization: Basic admin admin

###

# curl POST -i http://localhost:9000/user/login -H "Content-Type: application/json" -d '{"userName": "79", "password": "3"}'
POST http://localhost:9000/user/login
Content-Type: application/json

{
  "email": "demo7@com",
  "password": "abcdef"
}

###

POST http://localhost:9000/user/register
Content-Type: application/json

{
  "firstName": "Krishna",
  "lastName": "Thapa",
  "email": "demo@com",
  "password": "abc"
}

###

PUT http://localhost:9000/user/update
Content-Type: application/json

{
  "firstName": "krishna",
  "lastName": "Thapa",
  "email": "demo5@com",
  "password": "123"
}

###

GET http://localhost:9000/user/demo@com
###

GET http://localhost:9000/users
###

GET http://localhost:9000/user/toggle-to-admin/demo@com
###

DELETE http://localhost:9000/user/demo@com
###
