// Home page request
GET http://localhost:9000/

// Request to ping to check the HTTP response
###
GET http://localhost:9000/migrate
Authorization: Basic admin:admin

// Curl command to be used in the terminal
// curl -X GET -i http://localhost:9000/
// curl -X GET -i http://localhost:9000/admin/csv-quotes/5 -u "admin:admin"
// curl -X GET -i http://localhost:9000/admin/migrate -u "admin:admin"
// curl -X GET -i http://localhost:9000/admin/db-quotes -u "admin:admin"

// curl -X GET -i http://localhost:9000/admin/db-quotes?offset=0\&limit=10 -u "admin:admin"

// ===== User API endpoint
// curl -X GET -i http://localhost:9000/quote/random -u "user:user"