// Home page request
GET http://localhost:9000/

// Request to ping to check the HTTP response
###
GET http://localhost:9000/migrate
Authorization: Basic admin:admin

// Curl command to be used in the terminal
// curl -X GET -i http://localhost:9000/
// curl -X GET -i http://localhost:9000/admin/csv-quotes/5 -u "admin:admin"
// curl -X GET -i http://localhost:9000/admin/migrate -u "admin:admin"
// curl -X GET -i http://localhost:9000/admin/db-quotes -u "admin:admin"

// curl -X GET -i http://localhost:9000/admin/db-quotes?offset=0\&limit=10 -u "admin:admin"

// ===== User API endpoint
// curl -X GET -i http://localhost:9000/quote/random -u "admin:admin"
// curl -X GET -i http://localhost:9000/quote/e0a0c231-8b93-4bc5-8615-193e551a2703 -u "admin:admin"


// SELECT id FROM inspirational_quotes where 'dreams'=ANY(genre) order by random() limit 2;

// Auto completion
SELECT distinct a
FROM   inspirational_quotes l, unnest(genre) a
WHERE  lower(a) LIKE 'd%' ;
