version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

  # https://redis.io/
  redis:
    image: redis:latest
    container_name: redis-docker
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data:rw"
    command: >
      bash -c "redis-server --appendonly yes"

  # https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/installation.md
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./swagger:/swagger"
    environment:
      SWAGGER_JSON: /swagger/openapi.json
      BASE_URL: /swagger

  #  redoc-ui:
  #    image: redocly/redoc
  #    container_name: redoc-ui
  #    #restart: unless-stopped
  #    ports:
  #      - "18080:80"
  #    volumes:
  #      - "./swagger/openapi.json:/usr/share/nginx/html/openapi.json"
  #    environment:
  #      SPEC_URL: /openapi.json

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4-docker
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  redis-data:
    driver: local